# Generated by Django 3.2.13 on 2022-06-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.TextField(max_length=120)),
                ('password', models.TextField(max_length=120)),
                ('email', models.TextField(max_length=120)),
                ('fullname', models.TextField(max_length=120, null=True)),
            ],
        ),
    ]
