# Generated by Django 3.2.13 on 2022-06-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logins', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='Loginmodel',
        ),
    ]
